#!/bin/bash
#
# Setup a Python virtualenv for an application and uses pip to
# install it from a Wheel.
#
################################################################################

set -e

# Deploy hooks are run via absolute path, so taking dirname of this script will give us the path to
# our deploy_hooks directory.
. ../$(dirname $0)/aws_codedeploy_variables.sh

pushd $PKG_DIR >/dev/null

if [ ! -d "venv" ];
then
    virtualenv $PKG_DIR/venv
fi

source $PKG_DIR/venv/bin/activate
pip install --find-links=./ -U $PKG_NAME-*.whl

popd >/dev/null
