#!/bin/bash
#
# Start an application managed by supervisord
#
################################################################################

set -e

# Deploy hooks are run via absolute path, so taking dirname of this script will give us the path to
# our deploy_hooks directory.
. ../$(dirname $0)/aws_codedeploy_variables.sh

pushd $PKG_DIR >/dev/null

for proc in ${PROCESSES[@]}; do
    supervisorctl start $proc
done

popd >/dev/null
