#!/bin/bash
#
# Start a Node.js application managed by PM2
#
################################################################################

set -e

# Deploy hooks are run via absolute path, so taking dirname of this script will give us the path to
# our deploy_hooks directory.
. ../$(dirname $0)/common_variables.sh

pushd $PKG_DIR >/dev/null

# XXX Could be used to conditionally set environment here. We use 'production' NODE_ENV across the board for now.
NODE_ENV="production"
#if [ "$DEPLOYMENT_GROUP_NAME" == "fermina-dev" ];
#then
#  NODE_ENV="development"
#fi

for proc in ${PROCESSES[@]}; do
    NODE_ENV="$NODE_ENV" pm2 start server/app.coffee --name 'fermina'
done

popd >/dev/null
