#!/bin/bash
#
# Stop the webapp server
#
################################################################################

set -e

# Deploy hooks are run via absolute path, so taking dirname of this script will give us the path to
# our deploy_hooks directory.
. ../$(dirname $0)/common_variables.sh

pushd $PKG_DIR >/dev/null

for proc in ${PROCESSES[@]}; do
    supervisorctl stop $proc
done

popd >/dev/null
